### ISSUE TITLE
The Readme file might be better with fun pictures!

### ISSUE THREAD

**Issue by rachelmyers** [Joycetracy/ForFun#1]
I think everything is better with pictures. What do you think of this one?

![screen shot 2015-02-10 at 7 14 00 pm](https://cloud.githubusercontent.com/assets/209641/6123633/0293b2da-b159-11e4-9e9d-3a3490f19985.png)

**Comment by Joycetracy** [comment]
So cute...

**Comment by rachelmyers** [comment]
Cool! I'll start a pull request with some cute pictures, and see what you think of it!

**Comment by Joycetracy** [comment]
kitty1.png is added.
